import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Web3Modal from "web3modal";
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'
import { ethers } from 'ethers'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [walletConnected, setWalletConnected] = useState(false);
  const [ens, setEns] = useState("");
  const [address, setAddress] = useState("");

  let web3ModalRef = useRef()

  const getProviderorSigner = async () => {
     const provider = await web3ModalRef.current.connect();
     const web3provider = new ethers.providers.Web3Provider(provider)

     const { chainId } = await web3provider.getNetwork();

     if(chainId !== 5) {
      window.alert("Please connect to Goerli network");
      throw new Error("Different network");
     }

     const signer = web3provider.getSigner();
     const address = await signer.getAddress();
     setENSorAddress(address, web3provider);
     

  }

  const setENSorAddress = async (address, web3Provider) => {
     const _ens = await web3Provider.lookupAddress(address);

     if(_ens) {
      setEns(_ens);
     } else {
      setAddress(address);
     }
  }

  const connectWallet = async () => {
    try {
      await getProviderorSigner()
      setWalletConnected(true)
    } catch(err) {
      console.log(err);
    }
  }

  const renderButton = () => {
    if(!walletConnected) {
      return (
        <button onClick={connectWallet} className={styles.button}>
        Connect your wallet
      </button>
      )
    } else {
      return (
        <div>Wallet Connected</div>
      )
    }
  }

  useEffect(() => {
    if(!walletConnected) {
        web3ModalRef.current = new Web3Modal({
          network: "goerli",
          providerOptions: {},
          disableInjectedProvider: false
        })
        connectWallet();
    }
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div>
          <h1 className={styles.title}>
            Welcome to LearnWeb3 Punks {ens ? ens : address}!
          </h1>
          <div className={styles.description}>
            Its an NFT collection for LearnWeb3 Punks.
          </div>
          {renderButton()}
        </div>
        <div>
          <img className={styles.image} src="./learnweb3punks.png" />
        </div>
      </div>

      <footer className={styles.footer}>
        Made with &#10084; by LearnWeb3 Punks
      </footer>
    </div>
  )
}
